export const ITEM_DATA = {
	BOMB: {
		id: 'BOMB',
		name: 'Bomb',
		word: 'explode',
		type: 'consumable',
		rarity: 'common',
		baseValue: 2,
		radius: 200,
	},
	HEAVYROUNDS_PICKUP: {
		id: 'HEAVYROUNDS_PICKUP',
		name: 'Heavy Rounds',
		word: 'heavy',
		type: 'weapon',
		rarity: 'rare',
	},
	MEDKIT: {
		id: 'MEDKIT',
		name: 'Medkit',
		word: 'heal',
		type: 'consumable',
		rarity: 'common',
		baseValue: 10,
	},
	HEALTH_UP: {
		id: 'HEALTH_UP',
		name: 'Max Health Upgrade',
		word: 'endurance',
		type: 'upgrade',
		rarity: 'rare',
		baseValue: 10,
	},
	SHIELD: {
		id: 'SHIELD',
		name: 'Shield',
		word: 'protect',
		type: 'consumable',
		rarity: 'uncommon',
		baseValue: 5,
		duration: 10000,
	},
	RANDOM_WEAPON_DROP: {
		id: 'RANDOM_WEAPON_DROP',
		name: 'Random Weapon',
		word: 'weapon',
		type: 'weapon',
		rarity: 'common',
	},
};
